syntax = "proto3";

package gitproxy.v1;
import "google/protobuf/timestamp.proto";
import "buf/validate/validate.proto";

option go_package = "github.com/nylar/gitproxy/go/gen/gitproxy/v1;gitproxy";

service GitProxyService {
    rpc ListRepositories(ListRepositoriesRequest) returns (ListRepositoriesResponse) {}
    rpc GetRepository(GetRepositoryRequest) returns (GetRepositoryResponse) {}
    rpc CreateRepository(CreateRepositoryRequest) returns (CreateRepositoryResponse) {}
    rpc DeleteRepository(DeleteRepositoryRequest) returns (DeleteRepositoryResponse) {}
    rpc ListBranches(ListBranchesRequest) returns (ListBranchesResponse) {}
    rpc GetBranch(GetBranchRequest) returns (GetBranchResponse) {}
    rpc CreateBranch(CreateBranchRequest) returns (CreateBranchResponse) {}
    rpc DeleteBranch(DeleteBranchRequest) returns (DeleteBranchResponse) {}
    rpc ListTags(ListTagsRequest) returns (ListTagsResponse) {}
    rpc CreateTag(CreateTagRequest) returns (CreateTagResponse) {}
    rpc DeleteTag(DeleteTagRequest) returns (DeleteTagResponse) {}
    rpc CheckoutTag(CheckoutTagRequest) returns (CheckoutTagResponse) {}
    rpc Commit(CommitRequest) returns (CommitResponse) {}
    rpc Merge(MergeRequest) returns (MergeResponse) {}
    rpc Log(LogRequest) returns (LogResponse) {}
    rpc RevertMerge(RevertMergeRequest) returns (RevertMergeResponse) {}
    rpc Diff(DiffRequest) returns (DiffResponse) {}
    rpc Status(StatusRequest) returns (StatusResponse) {}
    rpc RevertCommit(RevertCommitRequest) returns (RevertCommitResponse) {}
}

message ListRepositoriesRequest {
}

message ListRepositoriesResponse {
    repeated Repository repositories = 1;
}

message GetRepositoryRequest {
    string namespace = 1 [(buf.validate.field).required = true];
}

message GetRepositoryResponse {
    Repository repository = 1;
}

message CreateRepositoryRequest {
    string namespace = 1 [(buf.validate.field).required = true];
}

message CreateRepositoryResponse {
    Repository repository = 1;
}

message DeleteRepositoryRequest {
    string namespace = 1 [(buf.validate.field).required = true];
}

message DeleteRepositoryResponse {}

message ListBranchesRequest {
    string namespace = 1 [(buf.validate.field).required = true];
}

message ListBranchesResponse {
    repeated Branch branches = 1;
}

message GetBranchRequest {
    string namespace = 1 [(buf.validate.field).required = true];
    string branch = 2 [(buf.validate.field).required = true];
}

message GetBranchResponse {
    Branch branch = 1;
}

message CreateBranchRequest {
    string namespace = 1 [(buf.validate.field).required = true];
    string branch = 2 [(buf.validate.field).required = true];
}

message CreateBranchResponse {
    Branch branch = 1 [(buf.validate.field).required = true];
}

message DeleteBranchRequest {
    string namespace = 1 [(buf.validate.field).required = true];
    string branch = 2 [(buf.validate.field).required = true];
}

message DeleteBranchResponse {}

message ListTagsRequest {
    string namespace = 1 [(buf.validate.field).required = true];
}

message ListTagsResponse {
    repeated string tags = 1;
}

message CreateTagRequest {
    string namespace = 1 [(buf.validate.field).required = true];
    string name = 2 [(buf.validate.field).required = true];
    optional string commit = 3;
    string message = 4 [(buf.validate.field).required = true];
    bool overwrite = 5 [(buf.validate.field).required = true];
    CommitAuthor author = 6 [(buf.validate.field).required = true];
}

message CreateTagResponse {}

message DeleteTagRequest {
    string namespace = 1 [(buf.validate.field).required = true];
    string name = 2 [(buf.validate.field).required = true];
}

message DeleteTagResponse {}

message CheckoutTagRequest {
    string namespace = 1 [(buf.validate.field).required = true];
    string name = 2 [(buf.validate.field).required = true];
}

message CheckoutTagResponse {
    string path = 1 [(buf.validate.field).required = true];
}

message CommitRequest {
    string namespace = 1 [(buf.validate.field).required = true];
    string branch = 2 [(buf.validate.field).required = true];
    string message = 3 [(buf.validate.field).required = true];
    CommitAuthor author = 4 [(buf.validate.field).required = true];
}

message CommitResponse {
    string commit = 1;
}

message MergeRequest {
    string namespace = 1 [(buf.validate.field).required = true];
    string branch = 2 [(buf.validate.field).required = true];
    bool dry_run = 3 [(buf.validate.field).required = true];
}

message MergeResponse {
    optional string commit = 1;
    repeated ConflictDiff conflicts = 2;
}

message RevertMergeRequest {
    string namespace = 1 [(buf.validate.field).required = true];
    string commit = 2 [(buf.validate.field).required = true];
}

message RevertMergeResponse {
    string commit = 1;
}

message LogRequest {
    enum Order {
        ORDER_UNSPECIFIED = 0;
        ORDER_NORMAL = 1;
        ORDER_REVERSE = 2;
    }

    string namespace = 1 [(buf.validate.field).required = true];
    optional string branch = 2;
    Order order = 3;
    optional string parent_branch = 4;
}

message LogResponse {
    repeated Log logs = 1;
}

message DiffRequest {
    string namespace = 1 [(buf.validate.field).required = true];
    string base_reference = 2 [(buf.validate.field).required = true];
    string target_reference = 3 [(buf.validate.field).required = true];
}

message DiffResponse {
    Diff diff = 1;
}

message StatusRequest {
    string namespace = 1 [(buf.validate.field).required = true];
    optional string branch = 2;
}

message StatusResponse {
    bool dirty = 1;
}

message RevertCommitRequest {
    string namespace = 1 [(buf.validate.field).required = true];
    string commit = 2 [(buf.validate.field).required = true];
    optional string branch = 3 [(buf.validate.field).required = true];
}

message RevertCommitResponse {
    string commit = 1;
}

message CommitAuthor {
    string name = 1 [(buf.validate.field).required = true];
    string email = 2 [(buf.validate.field).required = true];
}

message Log {
    string message = 1;
    CommitAuthor author = 2;
    string commit = 3;
    google.protobuf.Timestamp time = 4;
}

message Repository {
    string namespace = 1;
    string head_commit = 2;
    string path = 3;
}

message Branch {
    string name = 1;
    string path = 2;
}

message Diff {
    repeated DiffFile files = 1;
}

message DiffFile {
    enum Status {
        STATUS_UNSPECIFIED = 0;
        STATUS_UNMODIFIED = 1;
        STATUS_ADDED = 2;
        STATUS_DELETED = 3;
        STATUS_MODIFIED = 4;
        STATUS_RENAMED = 5;
        STATUS_COPIED = 6;
        STATUS_IGNORED = 7;
        STATUS_UNTRACKED = 8;
        STATUS_TYPECHANGE = 9;
        STATUS_UNREADABLE = 10;
        STATUS_CONFLICTED = 11;
    }

    Status status = 1;
    optional string old_path = 2;
    optional string new_path = 3;
    repeated DiffPatch patches = 4;
}

message DiffPatch {
    message Add {
        string path = 1;
        string value = 2;
    }

    message Remove {
        string path = 1;
    }

    message Replace {
        string path = 1;
        string value = 2;
    }

    message Move {
        string from = 1;
        string path = 2;
    }

    message Copy {
        string from = 1;
        string path = 2;
    }

    message Test {
        string path = 1;
        string value = 2;
    }

    oneof operation {
        Add add = 1;
        Remove remove = 2;
        Replace replace = 3;
        Move move = 4;
        Copy copy = 5;
        Test test = 6;
    }
}

message ConflictDiff {
    string path = 1;
    repeated DiffPatch ours = 2;
    repeated DiffPatch theirs = 3;
}
