syntax = "proto3";

package gitproxy.v1;
import "google/protobuf/timestamp.proto";

option go_package = "github.com/nylar/gitproxy/go/gen/gitproxy/v1;gitproxy";

service GitProxyService {
    rpc ListRepositories(ListRepositoriesRequest) returns (ListRepositoriesResponse) {}
    rpc CreateRepository(CreateRepositoryRequest) returns (CreateRepositoryResponse) {}
    rpc DeleteRepository(DeleteRepositoryRequest) returns (DeleteRepositoryResponse) {}
    rpc ListBranches(ListBranchesRequest) returns (ListBranchesResponse) {}
    rpc CreateBranch(CreateBranchRequest) returns (CreateBranchResponse) {}
    rpc DeleteBranch(DeleteBranchRequest) returns (DeleteBranchResponse) {}
    rpc ListTags(ListTagsRequest) returns (ListTagsResponse) {}
    rpc CreateTag(CreateTagRequest) returns (CreateTagResponse) {}
    rpc DeleteTag(DeleteTagRequest) returns (DeleteTagResponse) {}
    rpc CheckoutTag(CheckoutTagRequest) returns (CheckoutTagResponse) {}
    rpc Commit(CommitRequest) returns (CommitResponse) {}
    rpc Merge(MergeRequest) returns (MergeResponse) {}
    rpc Log(LogRequest) returns (LogResponse) {}
    rpc RevertMerge(RevertMergeRequest) returns (RevertMergeResponse) {}
    rpc Diff(DiffRequest) returns (DiffResponse) {}
}

message ListRepositoriesRequest {
}

message ListRepositoriesResponse {
    repeated Repository repositories = 1;
}

message CreateRepositoryRequest {
    string namespace = 1;
}

message CreateRepositoryResponse {
    Repository repository = 1;
}

message DeleteRepositoryRequest {
    string namespace = 1;
}

message DeleteRepositoryResponse {}

message ListBranchesRequest {
    string namespace = 1;
}

message ListBranchesResponse {
    repeated Branch branches = 1;
}

message CreateBranchRequest {
    string namespace = 1;
    string branch = 2;
}

message CreateBranchResponse {
    Branch branch = 1;
}

message DeleteBranchRequest {
    string namespace = 1;
    string branch = 2;
}

message DeleteBranchResponse {}

message ListTagsRequest {
    string namespace = 1;
}

message ListTagsResponse {
    repeated string tags = 1;
}

message CreateTagRequest {
    string namespace = 1;
    string name = 2;
    optional string commit = 3;
    string message = 4;
    bool overwrite = 5;
    CommitAuthor author = 6;
}

message CreateTagResponse {}

message DeleteTagRequest {
    string namespace = 1;
    string name = 2;
}

message DeleteTagResponse {}

message CheckoutTagRequest {
    string namespace = 1;
    string name = 2;
}

message CheckoutTagResponse {
    string path = 1;
}

message CommitRequest {
    string namespace = 1;
    string branch = 2;
    string message = 3;
    CommitAuthor author = 4;
}

message CommitResponse {
    string commit = 1;
}

message MergeRequest {
    string namespace = 1;
    string branch = 2;
}

message MergeResponse {
    string commit = 1;
}

message RevertMergeRequest {
    string namespace = 1;
    string commit = 2;
}

message RevertMergeResponse {
    string commit = 1;
}

message LogRequest {
    string namespace = 1;
    optional string branch = 2;
}

message LogResponse {
    repeated Log logs = 1;
}

message DiffRequest {
    string namespace = 1;
    optional string from_branch = 2;
    string to_branch = 3;
}

message DiffResponse {
    Diff diff = 1;
}

message CommitAuthor {
    string name = 1;
    string email = 2;
}

message Log {
    string message = 1;
    CommitAuthor author = 2;
    string commit = 3;
    google.protobuf.Timestamp time = 4;
}

message Repository {
    string namespace = 1;
    string head_commit = 2;
    string path = 3;
}

message Diff {
    uint64 files_changes = 1;
    uint64 insertions = 2;
    uint64 deletions = 3;
    repeated DiffDelta deltas = 4;
}

message DiffDelta {
    enum Status {
        STATUS_UNSPECIFIED = 0;
        STATUS_UNMODIFIED = 1;
        STATUS_ADDED = 2;
        STATUS_DELETED = 3;
        STATUS_MODIFIED = 4;
        STATUS_RENAMED = 5;
        STATUS_COPIED = 6;
        STATUS_IGNORED = 7;
        STATUS_UNTRACKED = 8;
        STATUS_TYPECHANGE = 9;
        STATUS_UNREADABLE = 10;
        STATUS_CONFLICTED = 11;
    }

    message File {
        optional string path = 1;
        uint64 size = 2;
    }

    message Line {
        enum Origin {
            ORIGIN_UNSPECIFIED = 0;
            ORIGIN_CONTEXT = 1;
            ORIGIN_ADDITION = 2;
            ORIGIN_DELETION = 3;
            ORIGIN_CONTEXTEOFNL = 4;
            ORIGIN_ADDEOFNL = 5;
            ORIGIN_DELETEEOFNL = 6;
            ORIGIN_FILEHEADER = 7;
            ORIGIN_HUNKHEADER = 8;
            ORIGIN_BINARY = 9;
        }
        optional uint32 old_line_number = 1;
        optional uint32 new_line_number = 2;
        uint32 number_lines = 3;
        int64 content_offset = 4;
        bytes content = 5;
        Origin origin = 6;
    }

    Status status = 1;
    File old_file = 2;
    File new_file = 3;
    repeated Line lines = 4;
}

message Branch {
    string name = 1;
    string path = 2;
}
